title: Fady Osama
#logo: assets/Fady-Professional.jpg
#description: 👋 Hi, I’m Fady Osama – a passionate Data Analyst with over 2 years of experience in data collection, cleaning, analysis, and visualization. I specialize in turning complex datasets into actionable insights to drive informed business decisions.

🎓 Currently pursuing my MBA in Digital Transformation at ESLSCA University (2022-2024), I bring a unique blend of technical expertise and strategic thinking to every project.

💡 Skills & Tools:

Programming: SQL
Visualization: Power BI
Data Processing: Excel, Google Sheets
Certifications: Google Data Analytics Professional Certificate, People Analytics (University of Pennsylvania)
💼 In my professional journey, I’ve worked on projects like:

Creating dynamic dashboards to track HR metrics and operations.
Transforming survey data into actionable recommendations for organizational development.
Spearheading data-driven initiatives for MSMEs to enhance customer retention and performance.
🚀 My mission is to leverage data to solve real-world problems and create impactful business solutions.

🌟 Interests: Volunteerism, sports, movies, and continuous learning.

📬 Feel free to connect with me to explore collaboration opportunities or simply share insights about data!
show_downloads: False
theme: jekyll-theme-minimal
