title: Fady Osama
logo: personal_photo.png

description: Hi, I’m Fady Osama, a Data Analyst with 2+ years of experience in SQL, Power BI, and Excel. I help businesses turn data into actionable insights, driving smarter decisions.
show_downloads: False
theme: jekyll-theme-minimal
