title: Fady Osama
#logo: /assets/Fady_Professional.jpg
#description: Hi, I’m Fady Osama, a Data Analyst with over 2 years of experience transforming data into actionable insights. I specialize in tools like Python, SQL, Power BI, and Tableau to help businesses make data-driven decisions.

Currently pursuing an MBA in Digital Transformation, I combine technical expertise with strategic thinking to solve real-world challenges. My professional journey includes creating dynamic dashboards, analyzing HR metrics, and driving impactful solutions for various industries.

Beyond work, I’m passionate about volunteerism, sports, and movies. Welcome to my space, where I share my projects, insights, and passion for all things data!
show_downloads: False
theme: jekyll-theme-minimal
